# Generated by Django 5.1.2 on 2024-11-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_rename_bomus_employee_bonus_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
